name: Update Monday.com on Git Push

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  update_monday:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Notify Monday.com
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
        run: |
          curl -X POST "https://api.monday.com/v2" \
          -H "Authorization: $MONDAY_API_KEY" \
          -H "Content-Type: application/json" \
          -data '{ 
            "query": "mutation { create_update (item_id: 1971940910, body: \"🚀 Test Update from API\") { id } }"
          }'